version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=hHsu27AsHfh99xqA121GH
      - POSTGRES_USER=couponsuser
      - POSTGRES_DB=coupons
    volumes:
      - coupons_pg_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
volumes:
  coupons_pg_data:
